export const PRISMA_CLIENT = Symbol('PRISMA_CLIENT');
export const BUSINESS_REPOSITORY = Symbol('BUSINESS_REPOSITORY');
export const BUSINESS_LOCATION_REPOSITORY = Symbol('BUSINESS_LOCATION_REPOSITORY');
export const SERVICE_CATEGORY_REPOSITORY = Symbol('SERVICE_CATEGORY_REPOSITORY');
export const SERVICE_REPOSITORY = Symbol('SERVICE_REPOSITORY');
export const BUSINESS_POLICY_REPOSITORY = Symbol('BUSINESS_POLICY_REPOSITORY');
