"use client";

import type { Service, ServiceCategory } from "@/api/types";
import { useTranslations } from "next-intl";

export function ServiceList({ services, categories, onEdit, onArchive, onRestore }: { services: Service[]; categories: ServiceCategory[]; onEdit: (service: Service) => void; onArchive: (service: Service) => void; onRestore: (service: Service) => void }) {
  const t = useTranslations("services");
  const categoryName = (categoryId: string) => categories.find((category) => category.id === categoryId)?.name ?? t("fields.unknownCategory");
  return <div className="grid gap-3 lg:grid-cols-2">{services.map((service) => <article key={service.id} className="rounded-lg border border-slate-200 bg-white p-4 shadow-sm"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><h2 className="truncate text-base font-semibold text-slate-900">{service.name}</h2><p className="mt-1 truncate text-sm text-slate-500">{service.slug}</p></div><span className={`shrink-0 rounded-full px-2 py-1 text-xs font-medium ${service.status === "active" ? "bg-emerald-50 text-emerald-700" : "bg-amber-50 text-amber-700"}`}>{service.status === "active" ? t("status.active") : t("status.archived")}</span></div><dl className="mt-4 grid grid-cols-1 gap-2 text-sm text-slate-600 sm:grid-cols-3"><div><dt className="text-xs text-slate-400">{t("fields.category")}</dt><dd>{categoryName(service.categoryId)}</dd></div><div><dt className="text-xs text-slate-400">{t("fields.duration")}</dt><dd>{t("fields.minutes", { count: service.durationMinutes })}</dd></div><div><dt className="text-xs text-slate-400">{t("fields.id")}</dt><dd className="truncate">{service.id}</dd></div>{service.archivedAt && <div><dt className="text-xs text-slate-400">{t("fields.archivedAt")}</dt><dd>{service.archivedAt}</dd></div>}</dl><div className="mt-4 flex gap-2 border-t border-slate-100 pt-3"><button type="button" onClick={() => onEdit(service)} className="rounded-md border border-slate-300 px-3 py-1.5 text-sm text-slate-700 hover:bg-slate-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-slate-500">{t("actions.edit")}</button>{service.status === "active" ? <button type="button" onClick={() => onArchive(service)} className="rounded-md border border-amber-200 px-3 py-1.5 text-sm text-amber-800 hover:bg-amber-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-amber-500">{t("actions.archive")}</button> : <button type="button" onClick={() => onRestore(service)} className="rounded-md border border-emerald-200 px-3 py-1.5 text-sm text-emerald-800 hover:bg-emerald-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-emerald-500">{t("actions.restore")}</button>}</div></article>)}</div>;
}